# Global settings
[build]
  # Build command
  command = "npm run build"   # Replace with your build command

  # Publish directory
  publish = "dist"            # Replace with your build output directory

# Headers configuration
[[headers]]
  # Define the source path or paths
  for = "/*"
  # Set response headers
  [headers.values]
    # Set Content-Security-Policy header
    Content-Security-Policy = "frame-ancestors 'none';"

# Environment variables
[build.environment]
  # Set environment variables for the build
  NODE_ENV = "production"
